# Generated by Django 6.0.4 on 2026-04-25 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('enchente', '🌊 Enchente'), ('incendio', '🔥 Incêndio'), ('seca', '☀️ Seca'), ('deslizamento', '⛰️ Deslizamento'), ('deslocamento', '🚶 Deslocamento Populacional'), ('epidemia', '🦠 Epidemia'), ('acidente', '🚨 Acidente em Massa'), ('outro', '⚠️ Outro')], max_length=20)),
                ('severidade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('critico', 'Crítico')], default='medio', max_length=10)),
                ('status', models.CharField(choices=[('ativo', 'Activo'), ('em_atendimento', 'Em Atendimento'), ('monitoramento', 'Em Monitoramento'), ('resolvido', 'Resolvido')], default='ativo', max_length=20)),
                ('provincia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pessoas_afetadas', models.PositiveIntegerField(default=0)),
                ('voluntarios_necessarios', models.PositiveIntegerField(default=5)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='incidentes/')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voluntarios_alocados', models.ManyToManyField(blank=True, related_name='missoes', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntarios.voluntario')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='incidentes.incidente')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioIntervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acoes_realizadas', models.TextField()),
                ('pessoas_ajudadas', models.PositiveIntegerField(default=0)),
                ('recursos_utilizados', models.TextField(blank=True)),
                ('problemas_encontrados', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntarios.voluntario')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Relatório de Intervenção',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
