# Generated by Django 6.0.4 on 2026-04-25 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('saude', '🏥 Saúde'), ('logistica', '🚛 Logística'), ('engenharia', '🔧 Engenharia'), ('alimentacao', '🍽️ Alimentação'), ('comunicacao', '📡 Comunicação'), ('educacao', '📚 Educação'), ('seguranca', '🛡️ Segurança'), ('psicologia', '🧠 Psicologia'), ('outro', '⭐ Outro')], max_length=20)),
                ('icone', models.CharField(default='⭐', max_length=10)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('provincia', models.CharField(choices=[('luanda', 'Luanda'), ('benguela', 'Benguela'), ('huila', 'Huíla'), ('cabinda', 'Cabinda'), ('zaire', 'Zaire'), ('uige', 'Uíge'), ('cuanza_norte', 'Cuanza Norte'), ('cuanza_sul', 'Cuanza Sul'), ('malanje', 'Malanje'), ('lunda_norte', 'Lunda Norte'), ('lunda_sul', 'Lunda Sul'), ('moxico', 'Moxico'), ('cuando_cubango', 'Cuando Cubango'), ('cunene', 'Cunene'), ('namibe', 'Namibe'), ('huambo', 'Huambo'), ('bie', 'Bié'), ('kwanza_sul', 'Kwanza Sul')], max_length=30)),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('disponibilidade', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='voluntarios/')),
                ('numero_bi', models.CharField(blank=True, max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('missoes_completadas', models.PositiveIntegerField(default=0)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('habilidades', models.ManyToManyField(blank=True, to='voluntarios.habilidade')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
