# Generated by Django 6.0.4 on 2026-04-25 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('agua', '💧 Água'), ('alimentos', '🥫 Alimentos'), ('roupas', '👕 Roupas'), ('medicamentos', '💊 Medicamentos'), ('higiene', '🧼 Higiene'), ('materiais', '🧱 Materiais de Construção'), ('geral', '📦 Geral')], default='geral', max_length=15)),
                ('provincia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('responsavel', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Activa'), ('cheio', 'Cheia'), ('fechado', 'Fechada')], default='ativo', max_length=10)),
                ('capacidade_total', models.PositiveIntegerField(default=1000)),
                ('capacidade_atual', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Central de Doação',
                'verbose_name_plural': 'Centrais de Doação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doador_nome', models.CharField(max_length=150)),
                ('doador_telefone', models.CharField(blank=True, max_length=25)),
                ('doador_anonimo', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('agua', '💧 Água'), ('alimentos', '🥫 Alimentos'), ('roupas', '👕 Roupas'), ('medicamentos', '💊 Medicamentos'), ('higiene', '🧼 Higiene'), ('dinheiro', '💰 Dinheiro'), ('outro', '📦 Outro')], default='outro', max_length=15)),
                ('descricao', models.TextField()),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('unidade', models.CharField(default='unidades', max_length=30)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entregue', models.BooleanField(default=True)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='doacoes.centraldoacao')),
            ],
            options={
                'verbose_name': 'Doação',
                'ordering': ['-data_doacao'],
            },
        ),
    ]
